In [21]:
import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt 
import plotly.express as px
import seaborn as sns

In [24]:
plt.figure(figsize=(500, 640))

In [10]:
df = pd.read_parquet('train_data.pqt')

In [9]:
df.columns

Index(['id', 'date', 'balance_amt_avg', 'balance_amt_max', 'balance_amt_min',
       'balance_amt_day_avg', 'channel_code', 'city', 'city_type',
       'index_city_code', 'ogrn_days_end_month', 'ogrn_days_end_quarter',
       'ogrn_month', 'ogrn_year', 'ft_registration_date', 'max_founderpres',
       'min_founderpres', 'ogrn_exist_months', 'okved', 'segment',
       'sum_of_paym_2m', 'sum_of_paym_6m', 'sum_of_paym_1y', 'sum_a_oper_1m',
       'cnt_a_oper_1m', 'sum_b_oper_1m', 'cnt_b_oper_1m', 'sum_c_oper_1m',
       'cnt_c_oper_1m', 'sum_deb_d_oper_1m', 'cnt_deb_d_oper_1m',
       'sum_cred_d_oper_1m', 'cnt_cred_d_oper_1m', 'sum_deb_e_oper_1m',
       'cnt_deb_e_oper_1m', 'cnt_days_deb_e_oper_1m', 'sum_cred_e_oper_1m',
       'cnt_cred_e_oper_1m', 'cnt_days_cred_e_oper_1m', 'sum_deb_f_oper_1m',
       'cnt_deb_f_oper_1m', 'cnt_days_deb_f_oper_1m', 'sum_cred_f_oper_1m',
       'cnt_cred_f_oper_1m', 'cnt_days_cred_f_oper_1m', 'sum_deb_g_oper_1m',
       'cnt_deb_g_oper_1m', 'cnt_days_deb_g_oper_1m', 'sum_cred_g_oper_1m',
       'cnt_cred_g_oper_1m', 'cnt_days_cred_g_oper_1m', 'sum_deb_h_oper_1m',
       'cnt_deb_h_oper_1m', 'cnt_days_deb_h_oper_1m', 'sum_cred_h_oper_1m',
       'cnt_cred_h_oper_1m', 'cnt_days_cred_h_oper_1m', 'sum_a_oper_3m',
       'cnt_a_oper_3m', 'sum_b_oper_3m', 'cnt_b_oper_3m', 'sum_c_oper_3m',
       'cnt_c_oper_3m', 'sum_deb_d_oper_3m', 'cnt_deb_d_oper_3m',
       'sum_cred_d_oper_3m', 'cnt_cred_d_oper_3m', 'sum_deb_e_oper_3m',
       'cnt_deb_e_oper_3m', 'cnt_days_deb_e_oper_3m', 'sum_cred_e_oper_3m',
       'cnt_cred_e_oper_3m', 'cnt_days_cred_e_oper_3m', 'sum_deb_f_oper_3m',
       'cnt_deb_f_oper_3m', 'cnt_days_deb_f_oper_3m', 'sum_cred_f_oper_3m',
       'cnt_cred_f_oper_3m', 'cnt_days_cred_f_oper_3m', 'sum_deb_g_oper_3m',
       'cnt_deb_g_oper_3m', 'cnt_days_deb_g_oper_3m', 'sum_cred_g_oper_3m',
       'cnt_cred_g_oper_3m', 'cnt_days_cred_g_oper_3m', 'sum_deb_h_oper_3m',
       'cnt_deb_h_oper_3m', 'cnt_days_deb_h_oper_3m', 'sum_cred_h_oper_3m',
       'cnt_cred_h_oper_3m', 'cnt_days_cred_h_oper_3m', 'start_cluster',
       'end_cluster'],
      dtype='object')

In [14]:
df

,id,date,balance_amt_avg,balance_amt_max,balance_amt_min,balance_amt_day_avg,channel_code,city,city_type,index_city_code,...,cnt_cred_g_oper_3m,cnt_days_cred_g_oper_3m,sum_deb_h_oper_3m,cnt_deb_h_oper_3m,cnt_days_deb_h_oper_3m,sum_cred_h_oper_3m,cnt_cred_h_oper_3m,cnt_days_cred_h_oper_3m,start_cluster,end_cluster
0,0,month_1,0.744845,0.705492,1.287207,0.748101,channel_code_5,city_23,city_type_0,index_city_code_39,...,0.951166,0.568681,0.897565,0.553624,0.774354,0.936506,0.295984,0.967947,"{α, γ}",{other}
1,0,month_2,1.049605,0.831916,2.458609,1.053805,channel_code_5,city_23,city_type_0,index_city_code_39,...,0.948812,0.499716,0.785029,0.551904,0.696576,0.990157,0.298873,0.945969,"{α, γ}",{other}
2,0,month_3,0.692653,0.740253,0.430042,0.695747,channel_code_5,city_23,city_type_0,index_city_code_39,...,0.946458,0.442244,0.877050,0.551044,0.663243,0.810065,0.294829,0.956958,"{α, γ}",{other}
3,1,month_1,-0.081586,-0.091860,-0.114040,-0.080890,channel_code_2,city_14,city_type_0,None,...,0.945281,0.407762,0.369318,0.567093,0.785465,-0.184002,0.253523,0.462452,{other},{other}
4,1,month_2,-0.094962,-0.100504,-0.119302,-0.094307,channel_code_2,city_14,city_type_0,None,...,0.946066,0.430750,0.067275,0.559928,0.696576,-0.183854,0.255545,0.495419,{other},{other}
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,199998,month_2,-0.156775,-0.204960,-0.125987,-0.156311,channel_code_9,city_14,city_type_0,None,...,NaN,NaN,-0.165588,NaN,NaN,-0.201123,NaN,NaN,{},{}
599996,199998,month_3,-0.156776,-0.204960,-0.125995,-0.156312,channel_code_9,city_14,city_type_0,None,...,0.944497,0.384773,-0.165588,0.546889,0.407687,-0.201123,0.250924,0.374540,{α},{}
599997,199999,month_1,-0.156712,-0.204913,-0.125831,-0.156248,channel_code_14,city_1876,city_type_0,index_city_code_195,...,NaN,NaN,-0.165588,NaN,NaN,-0.201123,NaN,NaN,{},{}
599998,199999,month_2,-0.156712,-0.204913,-0.125831,-0.156248,channel_code_14,city_1876,city_type_0,index_city_code_195,...,NaN,NaN,-0.165588,NaN,NaN,-0.201123,NaN,NaN,{},{}
599999,199999,month_3,-0.156712,-0.204913,-0.125831,-0.156248,channel_code_14,city_1876,city_type_0,index_city_code_195,...,NaN,NaN,-0.165588,NaN,NaN,-0.201123,NaN,NaN,{α},{}

In [12]:
list_num_fitch=[
'balance_amt_avg',
'balance_amt_max',
'balance_amt_min',
'balance_amt_day_avg',
'ogrn_days_end_month',
'ogrn_days_end_quarter',
'ft_registration_date',
'max_founderpres',
'min_founderpres',
'ogrn_exist_months',
'sum_of_paym_2m',
'sum_of_paym_6m',
'sum_of_paym_1y',
'sum_a_oper_1m',
'cnt_a_oper_1m',
'sum_b_oper_1m',
'cnt_b_oper_1m',
'sum_c_oper_1m',
'cnt_c_oper_1m',
'sum_deb_d_oper_1m',
'cnt_deb_d_oper_1m',
'sum_cred_d_oper_1m',
'cnt_cred_d_oper_1m',
'sum_deb_e_oper_1m',
'cnt_deb_e_oper_1m',
'cnt_days_deb_e_oper_1m',
'sum_cred_e_oper_1m',
'cnt_cred_e_oper_1m',
'cnt_days_cred_e_oper_1m',
'sum_deb_f_oper_1m',
'cnt_deb_f_oper_1m',
'cnt_days_deb_f_oper_1m',
'sum_cred_f_oper_1m',
'cnt_cred_f_oper_1m',
'cnt_days_cred_f_oper_1m',
'sum_deb_g_oper_1m',
'cnt_deb_g_oper_1m',
'cnt_days_deb_g_oper_1m',
'sum_cred_g_oper_1m',
'cnt_cred_g_oper_1m',
'cnt_days_cred_g_oper_1m',
'sum_deb_h_oper_1m',
'cnt_deb_h_oper_1m',
'cnt_days_deb_h_oper_1m',
'sum_cred_h_oper_1m',
'cnt_cred_h_oper_1m',
'cnt_days_cred_h_oper_1m',
'sum_a_oper_3m',
'cnt_a_oper_3m',
'sum_b_oper_3m',
'cnt_b_oper_3m',
'sum_c_oper_3m',
'cnt_c_oper_3m',
'sum_deb_d_oper_3m',
'cnt_deb_d_oper_3m',
'sum_cred_d_oper_3m',
'cnt_cred_d_oper_3m',
'sum_deb_e_oper_3m',
'cnt_deb_e_oper_3m',
'cnt_days_deb_e_oper_3m',
'sum_cred_e_oper_3m',
'cnt_cred_e_oper_3m',
'cnt_days_cred_e_oper_3m',
'sum_deb_f_oper_3m',
'cnt_deb_f_oper_3m',
'cnt_days_deb_f_oper_3m',
'sum_cred_f_oper_3m',
'cnt_cred_f_oper_3m',
'cnt_days_cred_f_oper_3m',
'sum_deb_g_oper_3m',
'cnt_deb_g_oper_3m',
'cnt_days_deb_g_oper_3m',
'sum_cred_g_oper_3m',
'cnt_cred_g_oper_3m',
'cnt_days_cred_g_oper_3m',
'sum_deb_h_oper_3m',
'cnt_deb_h_oper_3m',
'cnt_days_deb_h_oper_3m',
'sum_cred_h_oper_3m',
'cnt_cred_h_oper_3m',
'cnt_days_cred_h_oper_3m'
]

In [13]:
df[list_num_fitch].describe()

,balance_amt_avg,balance_amt_max,balance_amt_min,balance_amt_day_avg,ogrn_days_end_month,ogrn_days_end_quarter,ft_registration_date,max_founderpres,min_founderpres,ogrn_exist_months,...,cnt_days_deb_g_oper_3m,sum_cred_g_oper_3m,cnt_cred_g_oper_3m,cnt_days_cred_g_oper_3m,sum_deb_h_oper_3m,cnt_deb_h_oper_3m,cnt_days_deb_h_oper_3m,sum_cred_h_oper_3m,cnt_cred_h_oper_3m,cnt_days_cred_h_oper_3m
count,5.344230e+05,5.344230e+05,5.344230e+05,5.344230e+05,5.685270e+05,5.685270e+05,5.686400e+05,2.644080e+05,2.644080e+05,5.685270e+05,...,434748.000000,6.000000e+05,434748.000000,434748.000000,6.000000e+05,434748.000000,434748.000000,6.000000e+05,434748.000000,434748.000000
mean,5.291614e-18,-7.312532e-17,-3.959403e-17,-9.945043e-18,-6.117751e-17,1.003586e-17,-2.430370e-18,1.211971e-17,-3.759528e-17,4.538009e-17,...,0.810852,7.401487e-19,0.946172,0.410920,3.422448e-18,0.551292,0.507565,4.041212e-17,0.255424,0.456226
std,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000002e+00,1.000002e+00,1.000001e+00,...,0.145072,1.000001e+00,0.011519,0.080259,1.000001e+00,0.014255,0.156156,1.000001e+00,0.017320,0.136101
min,-1.567780e-01,-2.049624e-01,-1.259950e-01,-1.563145e-01,-1.649833e+00,-1.722458e+00,-1.081749e+00,-1.149405e+00,-1.075208e+00,-1.093396e+00,...,0.728507,-2.858428e-02,0.944497,0.384773,-1.655883e-01,0.546889,0.407687,-2.011323e-01,0.250924,0.374540
25%,-1.560927e-01,-2.042761e-01,-1.259122e-01,-1.556526e-01,-8.369370e-01,-8.706851e-01,-7.562179e-01,-7.608814e-01,-7.668686e-01,-7.628729e-01,...,0.728507,-2.858399e-02,0.944497,0.384773,-1.655881e-01,0.546889,0.407687,-2.011227e-01,0.250924,0.374540
50%,-1.499485e-01,-1.903097e-01,-1.248704e-01,-1.495861e-01,-2.404093e-02,-1.891231e-02,-3.151202e-01,-2.764884e-01,-2.965527e-01,-3.105786e-01,...,0.750485,-2.858399e-02,0.944497,0.384773,-1.655881e-01,0.547176,0.429909,-2.011227e-01,0.251501,0.396518
75%,-1.033781e-01,-1.063255e-01,-1.124800e-01,-1.033203e-01,7.888552e-01,8.715774e-01,4.040237e-01,4.519933e-01,4.554324e-01,4.026548e-01,...,0.816419,-2.858399e-02,0.944889,0.396267,-1.436181e-01,0.549755,0.541020,-1.384441e-01,0.254101,0.473441
max,1.542407e+02,1.174957e+02,9.145077e+01,1.547193e+02,1.834007e+00,1.800784e+00,3.032875e+00,3.376642e+00,3.592823e+00,3.029441e+00,...,1.728507,3.659603e+02,1.944497,1.384773,2.474600e+02,1.546889,1.407687,1.075818e+02,1.250924,1.374540

In [16]:
df_m1 = df[df.date=='month_1']

In [17]:
df_m1

,id,date,balance_amt_avg,balance_amt_max,balance_amt_min,balance_amt_day_avg,channel_code,city,city_type,index_city_code,...,cnt_cred_g_oper_3m,cnt_days_cred_g_oper_3m,sum_deb_h_oper_3m,cnt_deb_h_oper_3m,cnt_days_deb_h_oper_3m,sum_cred_h_oper_3m,cnt_cred_h_oper_3m,cnt_days_cred_h_oper_3m,start_cluster,end_cluster
0,0,month_1,0.744845,0.705492,1.287207,0.748101,channel_code_5,city_23,city_type_0,index_city_code_39,...,0.951166,0.568681,0.897565,0.553624,0.774354,0.936506,0.295984,0.967947,"{α, γ}",{other}
3,1,month_1,-0.081586,-0.091860,-0.114040,-0.080890,channel_code_2,city_14,city_type_0,None,...,0.945281,0.407762,0.369318,0.567093,0.785465,-0.184002,0.253523,0.462452,{other},{other}
6,2,month_1,-0.154685,-0.186795,-0.122805,-0.154215,channel_code_12,city_613,city_type_306,None,...,0.944497,0.384773,-0.165588,0.546889,0.407687,-0.178674,0.252657,0.440474,{α},{α}
9,3,month_1,-0.156643,-0.204861,-0.125660,-0.156179,channel_code_14,city_21,city_type_0,index_city_code_46,...,0.944497,0.384773,-0.165588,0.546889,0.407687,-0.201123,0.250924,0.374540,{α},{α}
12,4,month_1,-0.138847,-0.182486,-0.125630,-0.138328,channel_code_8,city_21,city_type_0,None,...,0.957443,0.672129,-0.078233,0.558209,0.707687,-0.178408,0.252946,0.440474,{α},{α}
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599985,199995,month_1,-0.067129,-0.108082,-0.031401,-0.066388,channel_code_9,city_20,city_type_0,index_city_code_28,...,0.944497,0.384773,-0.161095,0.547319,0.429909,-0.201123,0.250924,0.374540,"{α, η}",{other}
599988,199996,month_1,0.543173,0.382148,1.484547,0.545804,channel_code_14,city_3595,city_type_2778,index_city_code_48,...,0.944889,0.396267,-0.151699,0.553767,0.574354,-0.201123,0.250924,0.374540,"{α, γ}","{α, γ}"
599991,199997,month_1,-0.082159,-0.028263,-0.120011,-0.081465,channel_code_8,city_0,city_type_0,index_city_code_58,...,0.944889,0.396267,1.185234,0.571535,0.918798,0.955885,0.264788,0.693221,{other},{other}
599994,199998,month_1,-0.156775,-0.204960,-0.125987,-0.156311,channel_code_9,city_14,city_type_0,None,...,NaN,NaN,-0.165588,NaN,NaN,-0.201123,NaN,NaN,{},{}
599997,199999,month_1,-0.156712,-0.204913,-0.125831,-0.156248,channel_code_14,city_1876,city_type_0,index_city_code_195,...,NaN,NaN,-0.165588,NaN,NaN,-0.201123,NaN,NaN,{},{}

In [26]:
df_m1[list_num_fitch].corr()

,balance_amt_avg,balance_amt_max,balance_amt_min,balance_amt_day_avg,ogrn_days_end_month,ogrn_days_end_quarter,ft_registration_date,max_founderpres,min_founderpres,ogrn_exist_months,...,cnt_days_deb_g_oper_3m,sum_cred_g_oper_3m,cnt_cred_g_oper_3m,cnt_days_cred_g_oper_3m,sum_deb_h_oper_3m,cnt_deb_h_oper_3m,cnt_days_deb_h_oper_3m,sum_cred_h_oper_3m,cnt_cred_h_oper_3m,cnt_days_cred_h_oper_3m
balance_amt_avg,1.000000,0.863028,0.529008,0.999177,-0.000195,0.000615,0.053241,0.050267,0.039620,0.052407,...,0.067755,0.020880,0.043687,0.065436,0.229529,0.154903,0.181455,0.319225,0.122669,0.139093
balance_amt_max,0.863028,1.000000,0.440450,0.861794,-0.002962,0.001207,0.057169,0.045040,0.035138,0.056098,...,0.096474,0.075574,0.054264,0.080797,0.359994,0.222345,0.256765,0.461883,0.142763,0.179007
balance_amt_min,0.529008,0.440450,1.000000,0.529292,0.000273,0.002435,0.038542,0.036498,0.033695,0.037976,...,0.035006,0.006858,0.029845,0.045404,0.111832,0.068741,0.095848,0.158861,0.071814,0.082591
balance_amt_day_avg,0.999177,0.861794,0.529292,1.000000,-0.000121,0.000761,0.053374,0.050381,0.039713,0.052540,...,0.068161,0.020907,0.043814,0.065625,0.229369,0.155125,0.181862,0.319238,0.122864,0.139424
ogrn_days_end_month,-0.000195,-0.002962,0.000273,-0.000121,1.000000,0.286348,-0.003623,-0.004122,-0.005776,-0.000778,...,-0.004561,-0.000412,-0.004893,-0.005784,-0.001576,-0.004455,-0.006886,-0.002288,-0.006523,-0.009909
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
cnt_deb_h_oper_3m,0.154903,0.222345,0.068741,0.155125,-0.004455,0.002221,0.080837,0.055578,0.052394,0.079221,...,0.295716,0.029664,0.193616,0.270800,0.445835,1.000000,0.675986,0.437990,0.489946,0.472838
cnt_days_deb_h_oper_3m,0.181455,0.256765,0.095848,0.181862,-0.006886,0.005461,0.123254,0.072824,0.073592,0.120496,...,0.368181,0.038024,0.218678,0.350430,0.389560,0.675986,1.000000,0.396733,0.429792,0.621077
sum_cred_h_oper_3m,0.319225,0.461883,0.158861,0.319238,-0.002288,0.000256,0.032451,0.008812,0.003579,0.031316,...,0.146792,0.048012,0.093345,0.135681,0.703244,0.437990,0.396733,1.000000,0.362646,0.395242
cnt_cred_h_oper_3m,0.122669,0.142763,0.071814,0.122864,-0.006523,0.005436,0.056326,0.047281,0.045511,0.054971,...,0.187987,0.033374,0.406428,0.464754,0.299791,0.489946,0.429792,0.362646,1.000000,0.657366
cnt_days_cred_h_oper_3m,0.139093,0.179007,0.082591,0.139424,-0.009909,0.006143,0.080497,0.071082,0.072017,0.077776,...,0.260979,0.036999,0.308354,0.484669,0.299318,0.472838,0.621077,0.395242,0.657366,1.000000

In [28]:
df_m2 = df[df.date=='month_2']

In [29]:
df_m2

,id,date,balance_amt_avg,balance_amt_max,balance_amt_min,balance_amt_day_avg,channel_code,city,city_type,index_city_code,...,cnt_cred_g_oper_3m,cnt_days_cred_g_oper_3m,sum_deb_h_oper_3m,cnt_deb_h_oper_3m,cnt_days_deb_h_oper_3m,sum_cred_h_oper_3m,cnt_cred_h_oper_3m,cnt_days_cred_h_oper_3m,start_cluster,end_cluster
1,0,month_2,1.049605,0.831916,2.458609,1.053805,channel_code_5,city_23,city_type_0,index_city_code_39,...,0.948812,0.499716,0.785029,0.551904,0.696576,0.990157,0.298873,0.945969,"{α, γ}",{other}
4,1,month_2,-0.094962,-0.100504,-0.119302,-0.094307,channel_code_2,city_14,city_type_0,None,...,0.946066,0.430750,0.067275,0.559928,0.696576,-0.183854,0.255545,0.495419,{other},{other}
7,2,month_2,-0.152784,-0.193686,-0.122805,-0.152308,channel_code_12,city_613,city_type_306,None,...,0.944497,0.384773,-0.165588,0.546889,0.407687,-0.177854,0.252657,0.440474,{α},{α}
10,3,month_2,-0.156666,-0.204790,-0.125995,-0.156202,channel_code_14,city_21,city_type_0,index_city_code_46,...,0.944497,0.384773,-0.165588,0.546889,0.407687,-0.201123,0.250924,0.374540,{α},"{α, γ}"
13,4,month_2,-0.129233,-0.162965,-0.108713,-0.128684,channel_code_8,city_21,city_type_0,None,...,0.958620,0.683624,-0.078363,0.557779,0.641020,-0.176923,0.253234,0.451463,{α},{α}
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599986,199995,month_2,-0.004851,-0.053838,0.188375,-0.003917,channel_code_9,city_20,city_type_0,index_city_code_28,...,0.944497,0.384773,-0.133622,0.548465,0.474354,-0.201123,0.250924,0.374540,{other},{other}
599989,199996,month_2,0.413435,0.281704,1.162622,0.415664,channel_code_14,city_3595,city_type_2778,index_city_code_48,...,0.944889,0.396267,-0.154488,0.552334,0.552131,-0.201123,0.250924,0.374540,"{α, γ}","{α, γ}"
599992,199997,month_2,-0.111169,-0.041417,-0.125362,-0.110564,channel_code_8,city_0,city_type_0,index_city_code_58,...,0.944889,0.396267,0.638054,0.567093,0.829909,0.496713,0.261611,0.616298,{other},{other}
599995,199998,month_2,-0.156775,-0.204960,-0.125987,-0.156311,channel_code_9,city_14,city_type_0,None,...,NaN,NaN,-0.165588,NaN,NaN,-0.201123,NaN,NaN,{},{}
599998,199999,month_2,-0.156712,-0.204913,-0.125831,-0.156248,channel_code_14,city_1876,city_type_0,index_city_code_195,...,NaN,NaN,-0.165588,NaN,NaN,-0.201123,NaN,NaN,{},{}

In [30]:
df_m3 = df[df.date=='month_3']